Began File Integrity Encryption and Decryption proccesses
Nathan and Amanda:

Began Encrypting references files, part 1 works as intended.

NOTE: To test functionality for now you MUST Delete every file that has been created during the proccess and delete it, this is because a new key is generated every time the application launches. Delete the "enc" and "dec" prefixed files, as well as the "key.key" file before launching the application.

Always Select option 1 as soon as you launch the app to populate the files.

Issues:

LINE 147:

Populating the hashDict creates problems as new exit (\n\r) and prefix characters ('b') are introduced.

Error Received:
Traceback (most recent call last):
  File "C:\Users\natha\Documents\Capstone\SDNE-Capstone-2023\mainMenu.py", line 302, in <module>
    checkFile()
  File "C:\Users\natha\Documents\Capstone\SDNE-Capstone-2023\mainMenu.py", line 149, in checkFile
    hashDict.update({entry.split("|")[0].lstrip("b"): entry.split("|")[1].strip("\r\n")})
                                                      ~~~~^^^
IndexError: list index out of range